language: go
go:
  - 1.14.x
env:
  - GO111MODULE=on
matrix:
  allow_failures:
    - go: tip
script:
  - go test -v -mod=vendor ./vultr/...
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux