language: go
go:
  - 1.11.x
  - 1.12.x
  - tip
env:
  - GO111MODULE=on

matrix:
  allow_failures:
    - go: tip

script:
  - go test -v ./vultr/...

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
