name: notify-release

on:
  push:
    tags: v*

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release Notification
    steps:
      - run: |
          echo "{\"text\":\"Vultr-CLI : Release https://github.com/vultr/packer-builder-vultr/releases/tag/${{ GITHUB_REF#refs/*/ }} \"}" > mattermost.json
      - uses: mattermost/action-mattermost-notify@master
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          MATTERMOST_USERNAME: ${{ secrets.MATTERMOST_USERNAME}}
          MATTERMOST_ICON: ${{ secrets.MATTERMOST_ICON }}